/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import entidades.Direccion;
import entidades.Usuario;
import interfaces.INegocio;
import interfaces.IUsuariosDAO;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author focod
 */
public class Registro extends javax.swing.JFrame {

    private static final String ACTUALIZACION = "UPDATE";
    private static final String NUEVOREGISTRO = "NEWENTRY";
    private List<Usuario> usuarios;
    private List<Direccion> direcciones;
    private IUsuariosDAO usuariosDAO;
    private INegocio negocio;

    private Usuario usuario = null;

    /**
     * Creates new form Registro
     */
    public Registro(INegocio negocio) {
        this.negocio = negocio;
        initComponents();
    }

    private boolean verificarFormulario() {

        String error = "";

        if (textTelefono.getText().isEmpty()) {
            error = error + "Ingrese el teléfono.\n";
        }

        if (Boolean.valueOf(String.valueOf(passwordContrasena.getPassword()))) {
            error = error + "Ingrese la contraseña.\n";
        }

        if (textCalle.getText().isEmpty()) {
            error = error + "Ingrese la calle.\n";
        }

        if (textColonia.getText().isEmpty()) {
            error = error + "Ingrese la colonia.\n";
        }

        if (textNumero.getText().isEmpty()) {
            error = error + "Ingrese el numero.\n";
        }

        if (botonesSexo.toString().isEmpty()) {
            error = error + "Seleccione un sexo.\n";
        }

        if (datePickerFecha.getText().isEmpty()) {
            error = error + "Seleccione una fecha.\n";
        }

        if (!error.isEmpty()) {
            mostrarError(error);
            return false;
        }

        return true;
    }

    public void guardarUsuario() {

        if (!verificarFormulario()) {
            return;
        }

        if (negocio.verificarUsuarioTelefono(textTelefono.getText()) != null) {
            mostrarError("Ya existe un usuario con el mismo telefono");
            return;
        }

        String telefono = textTelefono.getText();
        String contrasena = String.valueOf(passwordContrasena.getPassword());
        String calle = textCalle.getText();
        String colonia = textColonia.getText();
        String numero = textNumero.getText();
        Direccion direccion = new Direccion(calle, colonia, numero);
        String sexo = null;
        if (botonMasculino.isSelected()) {
            sexo = "masculino";
        }
        if (botonFemenino.isSelected()) {
            sexo = "femenino";
        }
        if (botonOtro.isSelected()) {
            sexo = "otro";
        }
        LocalDate fecha = datePickerFecha.getDate();

        Usuario usuario = new Usuario(telefono, contrasena, sexo, fecha, direccion);
        usuario.generarId();

        boolean registroGuardado = negocio.guardarUsuario(usuario);

        if (!registroGuardado) {
            mostrarError("El usuario no pudo ser guardado");
        }

        JOptionPane.showMessageDialog(this, "Se ha registrado el usuario", "Información", JOptionPane.INFORMATION_MESSAGE);

    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesSexo = new javax.swing.ButtonGroup();
        labelRegistrarte = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        datePickerFecha = new com.github.lgooddatepicker.components.DatePicker();
        botonRegistrarte = new javax.swing.JButton();
        labelSexo = new javax.swing.JLabel();
        botonMasculino = new javax.swing.JRadioButton();
        botonFemenino = new javax.swing.JRadioButton();
        botonOtro = new javax.swing.JRadioButton();
        labelTelefono = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        labelCalle = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        passwordContrasena = new javax.swing.JPasswordField();
        textCalle = new javax.swing.JTextField();
        labelColonia = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        textColonia = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrarse");

        labelRegistrarte.setText("Registrarte");
        labelRegistrarte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        labelFecha.setText("Fecha de Nacimiento");

        botonRegistrarte.setText("Registrarte");
        botonRegistrarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarteActionPerformed(evt);
            }
        });

        labelSexo.setText("Sexo");

        botonesSexo.add(botonMasculino);
        botonMasculino.setText("Masculino");

        botonesSexo.add(botonFemenino);
        botonFemenino.setText("Femenino");

        botonesSexo.add(botonOtro);
        botonOtro.setText("Otro");

        labelTelefono.setText("Teléfono");

        labelContrasena.setText("Contraseña");

        labelCalle.setText("Calle");

        textTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelefonoKeyTyped(evt);
            }
        });

        labelColonia.setText("Colonia");

        labelNumero.setText("Número");

        textNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroKeyTyped(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFecha)
                            .addComponent(labelSexo)
                            .addComponent(labelTelefono)
                            .addComponent(labelContrasena)
                            .addComponent(labelCalle)
                            .addComponent(labelColonia)
                            .addComponent(labelNumero))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(botonFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(botonOtro))
                            .addComponent(textTelefono)
                            .addComponent(passwordContrasena)
                            .addComponent(textCalle)
                            .addComponent(datePickerFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textColonia)
                            .addComponent(textNumero)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(botonRegistrarte))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver)
                        .addGap(134, 134, 134)
                        .addComponent(labelRegistrarte)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelRegistrarte)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContrasena)
                    .addComponent(passwordContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCalle)
                    .addComponent(textCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColonia)
                    .addComponent(textColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMasculino)
                    .addComponent(botonFemenino)
                    .addComponent(botonOtro)
                    .addComponent(labelSexo))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha))
                .addGap(44, 44, 44)
                .addComponent(botonRegistrarte)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelefonoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (Character.isDigit(caracter)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_textTelefonoKeyTyped

    private void botonRegistrarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarteActionPerformed
        // TODO add your handling code here:
        guardarUsuario();
    }//GEN-LAST:event_botonRegistrarteActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void textNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (Character.isDigit(caracter)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_textNumeroKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonFemenino;
    private javax.swing.JRadioButton botonMasculino;
    private javax.swing.JRadioButton botonOtro;
    private javax.swing.JButton botonRegistrarte;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup botonesSexo;
    private com.github.lgooddatepicker.components.DatePicker datePickerFecha;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelColonia;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRegistrarte;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JPasswordField passwordContrasena;
    private javax.swing.JTextField textCalle;
    private javax.swing.JTextField textColonia;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
